server.port=58080
server.servlet.context-path=/hybrid-rag/api

spring.application.name=hybrid-rag-api
spring.config.import=optional:file:.env[.properties]

env.Qwen.apiKey=${ENV_QWEN_API_KEY:abc}
env.Qwen.baseUrl=${ENV_QWEN_BASE_URL:xyz}
